# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.CharField(max_length=255)),
                ('reject', models.BooleanField(default=False)),
                ('accept', models.BooleanField(default=False)),
            ],
        ),
    ]
